# Project: vortex-listener vortex-client

CC       = gcc.exe -g -Wall
OBJ      = test_01.o 

PROGRAMS = test_01.exe 

LIBS     = -Wall -g -L../src -laxl -L"../ns" -laxl-ns

INCS =  -I"." -I"../src" -I"../ns" -DAXL_NS_SUPPORT

CFLAGS   = $(INCS) -DVERSION=\""$(AXL_VERSION)"\" -Wall -g

.PHONY: all all-before all-after clean clean-custom

all: all-before $(PROGRAMS) all-after links

all-before:
	cd ../src;make -f Makefile.win

all-after:

clean: 
	${RM} $(OBJ) $(PROGRAMS) *.dll

test_01.exe: test_01.o
	$(CC) -mconsole $< -o $@ $(LIBS)

links:
	cp ../src/libaxl.dll .
	cp ../ns/libaxl-ns.dll .
%.o: %.c
	$(CC) -c $< -o $@ $(CFLAGS)

